language: python
python: 3.4
install: 
  - pip install -r requirements.txt
  - pip install pytest
script: pytest backend/HeadCount.py
service: mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
- mysql -u root -e 'CREATE DATABASE points;'
- mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
- mysql -u root -e "GRANT ALL ON stockmarket.* TO 'root'@'localhost';"
